{% set version = "0.2.2" %}

package:
  name: aitch
  version: {{ version }}

source:
  url: https://github.com/JaneliaSciComp/aitch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 29cf0b33b68630fe24bbadcde360aac6cf8a62a4a9fd2e8d927b6f3e83aafb21

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - test -f $PREFIX/bin/hstatus  # [unix]
    - if not exist "%PREFIX%\bin\hstatus.exe" exit 1  # [win]

about:
  home: https://github.com/JaneliaSciComp/aitch
  summary: local scheduler for heterogenous jobs
  description: |
    `aitch` (pronounced like the letter H) implements a light-weight
    cluster-style scheduler for use on a single workstation. Unlike `parallel`,
    `xargs`, and other similar utilities, which presume that all jobs use
    the same amount of resources, `aitch` permits one to request a different
    amount from an arbitrary number of unique kinds of resources. In effect
    it implements a counting semaphore for each resource and provides a
    means to adjust their values by non-negative integers.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - bjarthur
